const WMO = {
  0: { t: "Bezchmurnie", e: "☀️" },
  1: { t: "Prawie bez chmur", e: "🌤️" },
  2: { t: "Częściowo pochmurno", e: "⛅" },
  3: { t: "Pochmurno", e: "☁️" },
  45: { t: "Mgła", e: "🌫️" },
  48: { t: "Mgła szronowa", e: "🌫️" },
  51: { t: "Mżawka lekka", e: "🌦️" },
  53: { t: "Mżawka", e: "🌦️" },
  55: { t: "Mżawka silna", e: "🌧️" },
  61: { t: "Deszcz lekki", e: "🌦️" },
  63: { t: "Deszcz", e: "🌧️" },
  65: { t: "Ulewa", e: "🌧️" },
  71: { t: "Śnieg lekki", e: "🌨️" },
  73: { t: "Śnieg", e: "🌨️" },
  75: { t: "Śnieg mocny", e: "❄️" },
  80: { t: "Przelotny deszcz", e: "🌦️" },
  81: { t: "Przelotne opady", e: "🌦️" },
  82: { t: "Ulewy przelotne", e: "⛈️" },
  85: { t: "Przelotny śnieg", e: "🌨️" },
  86: { t: "Mocny śnieg", e: "❄️" },
  95: { t: "Burza", e: "⛈️" },
  96: { t: "Burza z gradem", e: "⛈️" },
  99: { t: "Silna burza z gradem", e: "⛈️" },
};
export const wmo = (code) => WMO[code] ?? { t: "Nieznany kod", e: "❔" };
